### ISSUE TITLE
Make this work with macOS catalina?

### ISSUE THREAD

**Issue by randomodbuild** [gwatts/pinfinder#101]
Do you think you can make this work with macOS catalina, as iTunes has been removed and backup function is now in finder?
Thanks!

**Comment by OPStellar** [comment]
I think it is noteworthy that ScreenTime also appears with Catalina. Perhaps the rout of a PinFinder for Time Machine backups should be explored?

**Comment by se9fault** [comment]
Using pinfinder on MacOS Catalina to find iOS device passcode has no issues. pinfinder only requires the backup files to work.
Finding MacOS Catalina passcode would be another thing I guess.

On that issue, one thing to note is that there are some messy stuff around "share screen time across devices" in iOS 13 and MacOS Catalina. With this turned on, it is possible that you would inherit some screen time passcode from a previous iOS device, and override your local screen time passcode. This "inherited" passcode has something do to with the iCloud account you logged in, so I guess that's the reason logging out iCloud might remove screen time passcode in @97.

I had that issue with my Mac, and Applecare said that there might be some features in the future that will allow us to manage screen time across our devices.

**Comment by OPStellar** [comment]
Thanks for the great news! That should make finding and running the backup a lot easier for the PinFinder build for Catalina.
I'm just thrilled that Apple is finally bothering to update parental controls by replacing it with ScreenTime. Parental Controls was the buggiest system ever!
Does the advent of Catalina hint at any newfound ability to recover the ScreenTime passcode for iOS 13? (Besides with "share screen time across devices," because PC users don't get Catalina— not that I am one, but such users do exist and desire a solution.)

**Comment by OPStellar** [comment]
Somebody upgraded my iOS form 12.4 to 13.1, and changed my ScreenTime passcode, and left in the morning for a week. Now I'm in the same boat with everybody else who has iOS 13.1 and, man, it's upsetting. I cannot reset my iPhone or its settings because it requires the ScreenTime passcode. What's worse is I cannot restore my previous backup because "there is not enough storage space available."
The *possibly good?* news is I have not updated my MacOS to OSX Catalina, and am still on High Sierra, AND I have a backup of an update to iOS 12.4 as well as a backup from when it was updated to 12.4. What steps must I take when upgrading to Catalina in order to override the iPhone's ScreenTime passcode?

iPhone Settings notes: iCloud's Family Sharing is set to 'on,' but is not activated for any accounts (a child account can be added, but I am unsure whether this will require inputting the ScreenTime passcode). Find My iPhone is set to 'off.' ScreenTime's Sharing Across Multiple Devices is set to 'off.' Changes to Accounts are set to 'allowed.'
iTunes settings notes: For some reason, it is auto-syncing my music when I connect my iPhone to my computer even though I do not have it set up to do that, and I cannot find the solution that allows me to change that setting except for where it is already unchecked. I did update my iTunes software so that it could connect with my iPhone, but I keep getting the 

Strange feature of iOS 13.1: You can view the ScreenTime settings without using the passcode, unlike in 12.4 where you had to insert the code to go past the first page.

@killgame I tried your method. It doesn't work.

**Comment by OPStellar** [comment]
Would it be possible to simply factory-reset my phone and restore the backup? Or would it keep the iOS 13.1 firmware?

**Comment by se9fault** [comment]
> Would it be possible to simply factory-reset my phone and restore the backup? Or would it keep the iOS 13.1 firmware?
> […](#)

You should check the FAQ on Pinfinder site, there are some links to the iPhone Backup Extractor site, regarding the iOS 13 passcode.
Resetting your phone and restore your backup will not change the system version on your device, and according to the FAQ it could get rid of the screen time passcode. 
If you want to backup now and are afraid to lose the previous 12.4 backup, just go to the directory and rename it, add a suffix and stuff. Then the new backup will be fresh, and you get to keep your old backup.

**Comment by afit** [comment]
Restoring the device will remove it in some cases, but there are a number of factors that can affect that, or lead it to propagate back from iCloud:

* The status of "Family Sharing" on the user's iCloud account
* Whether the "Family Sharing" user is marked as being under 13
* Whether you complete Screen Time setup on the restored device
* Whether "Share across devices" is enabled
* Whether there are other iOS 13+ / macOS 10.15+ devices on the account
* The OS version and Screen Time configuration in the backup you restore

Broadly speaking, though, if you restore from a backup, don't have "Family Sharing" enabled, and don't re-enable Screen Time, you should be good.

It's not clear that this will remain consistent in future iOS 13 updates, as Apple made a few tweaks in 13.1 and 13.2. (I wrote the article linked on the FAQ. That describes a paid product which will remove the code irrespective of the caveats above both for iOS and macOS, but it also covers a free path using a restore, subject to those caveats. I've been updating the guide since 2014 and tend to patch it every few weeks with new information.)

To answer @OPStellar's question: if you update to Catalina you'll be prompted to enable Screen Time when you first log in. Guess what'll happen if you choose to set it up on the Mac? "Set Up Later" is the option you want. It can be put off indefinitely.

**Comment by killgame** [comment]
Well the best thing you can do is try different combinations like brute
forcing. If your screen time is shared with MacBook then try brute forcing
in Mac, as with Mac you can change time to bypass the back off time pause.

**Comment by killgame** [comment]
Even if it is not shared you can turn on to share with other devices on
Mac. That will sync with the iPhone passcode and then try brute forcing.

**Comment by killgame** [comment]
I’m always wary of paid softwares tbh. Advised to stay clear.

**Comment by gwatts** [comment]
@killgame you're right to be wary of many of the commercial "solutions" around this area - However, I will add that I trust the software that @afit references - I've met him in person and know they do quality work.   If you find yourself in such a bind that you'd consider paying for commercial software to solve the problem for you, now that pinfinder doesn't support iOS 13, then that would be my recommendation.

Take a look at the [FAQ](https://pinfinder.net/faq.html#ios13) for a link.

**Comment by killgame** [comment]
if thats the case it is worth giving a try.
