### ISSUE TITLE
downloading

### ISSUE THREAD

**Issue by adameims** [gwatts/pinfinder#17]
i really need this program but when i try and download it it says safari can;t make a secure connection to your server?? how do i overcome this?
a

**Comment by adameims** [comment]
Resolved this but now I can't 'open with' as I have no application that can read it. What application should I download to read the file format?

**Comment by gwatts** [comment]
Hi

So, first i want to make sure you definitely have the right file - I assume you're using Mac, so that should be this one https://github.com/gwatts/pinfinder/releases/download/1.5.0/pinfinder-mac-1.5.0.tar.gz

Safari should download that file and if you click on the link from the Safari download button, it should automatically extract it to a file called `pinfinder` in your `Downloads` directory.

You'll need to find that in Finder, right-click on it and select `Open` for it to run, accepting the security warning it provides, at which point it should do it's thing and display any passcodes it finds.

If that doesn't work, please attach a screenshot that shows the error.

Thanks

**Comment by adameims** [comment]
Thanks gareth. I've worked out it wasn't downloading because our internet filter was blocking itv- solved that, but discovered the backup is encrypted so it doesn't show the passcode and I can't seem to be able to disengage the encryption. Is there a way to do this?

**Comment by gwatts** [comment]
If the iTunes backup is encrypted, then you'll need the original encryption password used with iTunes to disable it; i'm not sure what tools exist to help recover that if you don't know what it is.

Alternatively you may be able to make a new backup to another machine (or a different user account on the same machine) and run pinfinder from that account.

**Comment by MottyBig** [comment]
Just saying, once you set up a password for a encrypted backup, you can't make any new backups that are not encrypted. You'll need to password to do a unencrypted backup.

**Comment by adameims** [comment]
so my only option is to restore to original default....
