### ISSUE TITLE
Mismatch Error 

### ISSUE THREAD

**Issue by Troph-eus** [gwatts/pinfinder#20]
I created an unencrypted backup of my iphone6 which has a restrictions passcode I cant recall.  I ran pinfinder on my iMac running OS X El Capitan 10.11.6.  Below is the result I get: 

IOS DEVICE                                BACKUP TIME                RESTRICTIONS PASSCODE
AAA iPhone 6                              Jul 21, 2017 01:39 AM CDT  plist: type mismatch: tried to decode string into value of type struct { Key []uint8 "plist:\"RestrictionsPasswordKey\""; Salt []uint8 "plist:\"RestrictionsPasswordSalt\"" }

I dont see a 4 digit code here.  Can you please help?
Thank you in advance. 
Tropheus

**Comment by gwatts** [comment]
Odd; you're not the first to see this error but i've yet to reproduce it .. could you download this diagnostic build of pinfinder? https://gwatts.com/pinfinder/pinfinder-1.5.1dev2.dmg

This should create a file called `pinfinder-debug.zip` in your home directory which contains some debugging information, including the file that pinfinder is trying to decode.  It does not include any other personal information, but of course feel free to inspect the contents of the zip file.

If you're comfortable emailing that zip file to me at `gareth@omnipotent.net` I stand a good chance of being able to reproduce the problem here and come up with a fix

Thanks!

**Comment by Troph-eus** [comment]
Thanks for being willing to help, but I'm not comfortable emailing you my unencrypted phone backup.

**Comment by gwatts** [comment]
to be clear the file does not include any part of your backup other than the bit that holds the passcode - the most i could extract is that passcode.  as a result the zip file is tiny

please inspect the contents of the generated zip to confirm.

other only stuff included is a list of hash names (so i can tell if the required file is even in there) and the output from pinfinder that you see on screen

**Comment by Troph-eus** [comment]
I misunderstood.  I thought you needed the zip file "and the file that pinfinder is trying to decode".

**Comment by gwatts** [comment]
ah sorry - yeah the zip includes just the one tiny piece of the backup that includes the passcode we want to extract - The backup itself consists of hundreds of individual files, and we're only interested in that one 

In the backup zip you'll see that as file called something like `backups/ff1eb7b7af3668b781b41cdfe9bae946a61c01b2d/39/398bc9c2aeeab4cb0c12ada0f52eea12cf14f40b `

which contains 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>RestrictionsPasswordKey</key>
	<data>
	LigOGYOYCMEbr2+bmFnFbZk7e1k=
	</data>
	<key>RestrictionsPasswordSalt</key>
	<data>
	VK3kOg==
	</data>
</dict>
</plist>
```

**Comment by Troph-eus** [comment]
File requested was sent to your email right after my last post.  Let me know if you didn't get this file.

**Comment by gwatts** [comment]
Thanks - Looks like it got trapped in my spam filter, but I have it now; will take a look

**Comment by gwatts** [comment]
Interesting - It looks like the file containing the passcode is still encrypted, even though you've made an unencrypted backup.  Did you actually use the `Backup` button to take the backup, or `Sync`?

Reason i ask is that the status file in that backup directory says:

```
{
  "SnapshotState" => "finished"
  "Version" => "3.2"
  "IsFullBackup" => 0
  "UUID" => "..."
  "Date" => 2017-07-21 06:39:52 +0000
  "BackupState" => "new"
}
```

which implies that it's a partial backup/snapshot rather than a complete one - I haven't tested it, but I'm wondering if you had an encrypted backup, unchecked the checkbox and then hit `Sync` instead of `Backup` it might not have decrypted all the files needed

**Comment by Troph-eus** [comment]
Definitely not a sync, I am creating the backup from the iTunes device summary page.  I hit "Back Up Now", but I have created another backup anyway.  

I closed iTunes.  I ran Pinfinder and this time there was a 4 digit pin. I tried that pin and it worked!!!  Finally, restrictions hell is over!  I'm not sure why it worked today and not last time, but I am excited to have a good result here.  

Thank you GWatts!

**Comment by gwatts** [comment]
Great that you got it working!

So the solution in the end was to move the old backup files out of the way, which forced iTunes to create an entirely fresh backup?  That would make sense to me.

I'll update pinfinder to detect this condition in any event and hopefully offer some better advice to people who come across it in the future

Thanks for the help debugging :-)

**Comment by gwatts** [comment]
To update this; 1.6.0 now supports encrypted backups so this problem should not arise in the future.
