### ISSUE TITLE
Pinfinder found pin but pin did not work

### ISSUE THREAD

**Issue by boomerinclearlake** [gwatts/pinfinder#59]
Pinfinder found the Screen Time passcode but when I entered into my iPhone, it was not accepted.

**Comment by gwatts** [comment]
Are you sure the backup of the phone is recent?  It usually means the code has been changed since the backup was taken

**Comment by boomerinclearlake** [comment]
Yes - I followed instructions on the website and made encrypted backup first then used PinFinder.  Problem was resolved last night when:  1.  I updated to IOS 12.1.4 from 12.0
 2.  after having my ninth passcode attempt rejected by the Content & Privacy Restrictions of Screen Time, I went back to the Change Screen Time Passcode section.  I used touchid and it asked me to enter new passcode which now works.  This was the first time I had seen a TouchID request in Screen Time and neither of the Apple Tech support folks suggested doing this so not sure if this is new in 12.1.4 or not.  Anyhow, I'm glad the problem is resolved but I started out thinking I had forgotten the passcode but not believe there is an IOS bug.  

Thanks for your quick response and making this program available.

**Comment by gwatts** [comment]
Very strange, but glad you got it working -  Thanks for letting me know!

**Comment by datavizier** [comment]
Actually, my experience agrees with this.  I was frustrated by this new Screen Time passcode requirement.  I ran pinfinder (I had to back up my iPad Pro to my Macbook, rather than iCloud, to follow the instructions) and it found a pin, (gave readouts for my iPod Touch as well) but that pin did not work under Settings / Touch ID & Passcode.  It did work under Settings/Screen Time, which is what I needed.  I don't understand why that would be true, but it looks like Apple's bug, not yours.  I have had this issue only since Apple started annoying me with this Screen Time app.  Evidently they have released it without testing, or maybe explaining.  But, I think you should let users know about this trick.  Thanks.  I am running Mojave 10.14.4 OS and 12.2 iOS.
