### ISSUE TITLE
ipad is disabled

### ISSUE THREAD

**Issue by datavizier** [gwatts/pinfinder#68]

**Comment by datavizier** [comment]
Actually, I just posted a thanks. However, I just had a scare. To recap, I ran pinfinder after backing up my iPad Pro (12.2 iOS) to iTunes on Mac (10.14.4 OS) (instead of to iCloud).  Allowed Terminal access to disk and installed and ran pinfinder (had to allow non-listed developer as well).  The four digit code did not work under Settings / Touch ID & Passcode (passcode attempt failed, 2 Failed Passcode Attempts, etc.) , but did work under /Screen Time/Change Screen Time Passcode.  Shortly thereafter I got a screen display on the iPad, iPad LOCKED. YIKES!  But it seems to have come back once I entered my iPad password (NOT the pin).  I have now been able to turn off screen time. SO HAPPY to be shut of that.

So, thanks!  I wonder if Apple is now storing the Screen Time pin in the slot where the restrictions pass pin used to be?  And put the old one somewhere else. Maybe using a list.  I can see why they would be different, but I am not eager to explore the question, knowing as little as I do.  (I won't expect you to be able to run pinfinder on an iCloud backup, although that would be lots of grins.)

I would like to support you.  I suspect many of us have stopped using PayPal once Google started to increase the amount of personal information required to use it.  I will look into the Amazon alternative you now offer, but I've not used that before.

**Comment by gwatts** [comment]
Hi - Thanks for the feedback

The restrictions passcode was/is stored in a completely different location to the screen time one, as far as the backup goes; they haven't moved it since launching it though; as far as I know they just have the one slot they store it in.

The passcode under "Touch ID & Passcode" is the one used to unlock the device - That's not stored in the backup and can't be recovered (and pinfinder has nothing to do with that one), so I think that's probably the confusion there

Not sure about your Google/Paypal relationship claim (they have no relationship to each other from a business/ownership perspective afaik) - Actually to donate via paypal shouldn't even require you to have a Paypal account at this point, though you can login with one if you like.

The Amazon option is just convenient if you already have an Amazon account.

Appreciate your support in either case :-)
