### ISSUE TITLE
Windows ios 12.4.1

### ISSUE THREAD

**Issue by Brunioni** [gwatts/pinfinder#93]
I made a backup, three times. Then I went to the Pinfinder app but it said:
![Screenshot (7)](https://user-images.githubusercontent.com/55402459/64974313-db7eb700-d8ac-11e9-9755-aaa1f76aea8e.png)

pls help :)

**Comment by gwatts** [comment]
Are you sure your'e backing up the right device?  If you're set a passcode for a child's device on your phone, you actually need to take the backup of the child's device.

Also if you've since updated to iOS 13, you'll want to take a look at #77 as pinfinder does not support iOS 13 or later at the curren time.
