### ISSUE TITLE
Pinfinder reports no passcode with iOS 12 backup

### ISSUE THREAD

**Issue by soh** [gwatts/pinfinder#94]
I'm using pinfinder on Mac OS 10.14.1; iTunes 12.9.0.164; iOS 12.0. I've made an encrypted local backup. Pinfinder runs and it accepts my "iTunes Encryption Password." It works a minute and gives me this:

    IOS DEVICE                           IOS      BACKUP TIME                RESTRICTIONS PASSCODE
    Lola Limekiller                      12.0     Sep 16, 2019 10:50 PM PDT  none

I do have a passcode, and iOS is still giving me the finger for forgetting it. Any advice? TIA!

**Comment by gwatts** [comment]
This is usually caused by a couple of things - Either backing up the parent's device, instead of a child's (the passcode is stored on the child's device if you're managing a family's screen time functionality, so that's the device you actually need to backup)

Or something went wrogn with the backup - In which case making a fresh backup is a good option to try.

**Comment by soh** [comment]
Sweet; I did get the passcode from an encrypted backup of the kid's phone. Thank you!

Consider adding this to the FAQ: https://pinfinder.net/faq.html

**Comment by gwatts** [comment]
Great!  Glad it helped - it's actually already in the faq under `Pinfinder tells me my passcode is "none"`

**Comment by soh** [comment]
Ha! You're so right!
