### ISSUE TITLE
Still can't find the Screentime Password 

### ISSUE THREAD

**Issue by Roshinjose167** [gwatts/pinfinder#95]

**Comment by Roshinjose167** [comment]
I have tried all of the steps that you guys provided, I'm using macOS Mojave and IOS 13

Kindly check the error Screenshots 

Terminal Error -  https://prnt.sc/p8r3g9

System Pre - https://prnt.sc/p8r3o7

Please help me to resolve this issue 

Thanks so much!!

**Comment by gwatts** [comment]
So you have two problems here - The error you're getting is because you need to grant access to "Terminal", not to "Pinfinder" in order to grant the permissions needed

However, as you're running iOS 13 you're still out of luck unfortunately as iOS 13 does not include the passcode in the backup, so pinfinder cannot recover it - See #77 

Sorry!
